apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypyapp
  labels:
    app: mypyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypyapp
  template:
    metadata:
      labels:
        app: mypyapp
    spec:
      containers:
      - name: mypyapp
        image: jcrelling/cnfdemopyapp:1aff4ddf9bc33d89bcccdc6a7510ed623214ca14
        ports:
        - containerPort: 80
