apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypyapp
  labels:
    app: mypyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypyapp
  template:
    metadata:
      labels:
        app: mypyapp
    spec:
      containers:
      - name: mypyapp
        image: jcrelling/cnfdemopyapp:5c682625aabb468940dc6c98c42c8e19bff02d39
        ports:
        - containerPort: 80
